### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

<> 2021-01-15T152646.201.json
<> 2021-01-15T152501.201.json
<> 2021-01-15T135455.201.json
<> 2021-01-15T121143.401.json
<> 2021-01-15T121133.401.json


### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

<> 2021-01-15T135449.409.json


### Delete Task
DELETE http://localhost:3000/tasks/4

<> 2021-01-15T144245.404.json


### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodW5ndXMiLCJpYXQiOjE2MTEyNjE4NTUsImV4cCI6MTYxMTI2NTQ1NX0.f0gweiZx5x5UOdm2QjdWGZFyW708mOzJGaKMGJEZJlo

{
  "title": "chungle test 2",
  "description": "yet again"
}


### Get All Tasks
GET http://localhost:3000/tasks/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplbmdoaXMiLCJpYXQiOjE2MTEyNjM0NjgsImV4cCI6MTYxMTI2NzA2OH0.pOLuC1ps4pJbhE3VVN9EZFPFoxaA7aYsOcjsZ79Cu_M


### Get Filtered Tasks
GET http://localhost:3000/tasks?status=IN_PROGRESS&search=chain


### Post Task (test)
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplbmdoaXMiLCJpYXQiOjE2MTEyNTEyNTIsImV4cCI6MTYxMTI1NDg1Mn0.Xxck-UBhfp5_d1L0hF2q6G4njG9R093dX3uqGkDOPXY

{
  "title": "test title",
  "description": "test description"
}


### Edit Task
PATCH http://localhost:3000/tasks/1/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### Token Test
POST http://localhost:3000/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplbmdoaXMiLCJpYXQiOjE2MTEyNTEyNTIsImV4cCI6MTYxMTI1NDg1Mn0.Xxck-UBhfp5_d1L0hF2q6G4njG9R093dX3uqGkDOPXY

{

}

<> 2021-01-15T152727.401.json
<> 2021-01-15T152613.401.json




