### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

<> 2021-01-15T152646.201.json
<> 2021-01-15T152501.201.json
<> 2021-01-15T135455.201.json
<> 2021-01-15T121143.401.json
<> 2021-01-15T121133.401.json


### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}"
}

<> 2021-01-15T135449.409.json


### Delete Task
DELETE http://localhost:3000/tasks/5
Authorization: Bearer {{token}}

<> 2021-01-15T144245.404.json


### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "chungle test 2",
  "description": "yet again"
}


### Get All Tasks
GET http://localhost:3000/tasks/
Accept: application/json
Authorization: Bearer {{token}}


### Get Filtered Tasks
GET http://localhost:3000/tasks?status=IN_PROGRESS&search=chain


### Post Task (test)
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "test title",
  "description": "test description"
}


### Edit Task
PATCH http://localhost:3000/tasks/4/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "IN_PROGRESS"
}




